-- MySQL Script generated by MySQL Workbench
-- Wed May 17 19:32:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emaildb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emaildb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emaildb` DEFAULT CHARACTER SET utf8 ;
USE `emaildb` ;

-- -----------------------------------------------------
-- Table `emaildb`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emaildb`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `emaildb`.`emails` (`id`, `address`, `created_at`) VALUES ('1', 'michael@codingdojo.com', '2013-06-24 00:00:00');
INSERT INTO `emaildb`.`emails` (`id`, `address`, `created_at`) VALUES ('2', 'dexter@codingdojo.com', '2013-06-22 00:00:00');
INSERT INTO `emaildb`.`emails` (`id`, `address`, `created_at`) VALUES ('3', 'eylem@codingdojo.com', '2013-06-20 00:00:00');
